apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: smbk7d41f-nodejs
  janus-idp.io/tekton: smbk7d41f-nodejs
  backstage.io/kubernetes-id: smbk7d41f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: smbk7d41f-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
