apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: smbk7d41f-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: smbk7d41f-nodejs 
  name: smbk7d41f-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: smbk7d41f-nodejs 
